### ISSUE TITLE
convert this project to swift 4

### ISSUE THREAD

**Issue by balitax** [balitax/Google-Place-Auto-Complete#1]

**Comment by NSMyself** [comment]
May I do this one?

**Comment by balitax** [comment]
yes, @NSMyself you can try

**Comment by ostanik** [comment]
is it done @NSMyself or can I do it?

**Comment by NSMyself** [comment]
Sorry folks, I'm swamped with work and still haven't been able to do it.

Go for it @ostanik , it's all yours 👍

**Comment by ostanik** [comment]
@balitax this project is already in Swift 4 :)
what exactly you want to change it?

**Comment by balitax** [comment]
sorry, forget to close this issue 😛 @ostanik
