### ISSUE TITLE
Uddate readme and screenshoot sample (good with iphne x)

### ISSUE THREAD

**Issue by balitax** [balitax/Google-Place-Auto-Complete#4]

**Comment by NSMyself** [comment]
Just added a [PR](https://github.com/balitax/Google-Place-Auto-Complete/pull/5) for this task

**Comment by balitax** [comment]
thanks for your  [PR](https://github.com/balitax/Google-Place-Auto-Complete/pull/5) @NSMyself 

i close this issue
